# Home Assistant configuration for testing
homeassistant:
  name: Test Home
  latitude: 0
  longitude: 0
  elevation: 0
  unit_system: metric
  time_zone: UTC

# Include our test files
include:
  - test-position-tracking.yaml
  - test-goto-definition.yaml

# Basic configuration entities for testing
light:
  - platform: demo
    name: Demo Light

sensor:
  - platform: demo
    name: Demo Sensor

automation: !include test-goto-definition.yaml
