# Test file for secrets validation
automation:
  - alias: "Test Secrets Validation"
    trigger:
      - platform: state
        entity_id: binary_sensor.motion
        to: "on"
    action:
      - service: notify.email
        data:
          message: "Motion detected!"
          username: !secret email_username     # This doesn't exist in secrets.yaml - should be flagged
          password: !secret email_password     # This exists - should not be flagged
      - service: mqtt.publish
        data:
          topic: "home/motion"
          payload: "detected"
          username: !secret mqtt_user          # This exists - should not be flagged
          password: !secret unknown_secret     # This doesn't exist - should be flagged
      - service: notify.telegram
        data:
          message: "Motion in living room"
          api_token: !secret telegram_token    # This exists - should not be flagged
          chat_id: !secret telegram_chat       # This doesn't exist - should be flagged

script:
  backup_database:
    sequence:
      - service: shell_command.backup
        data:
          password: !secret database_password  # This exists - should not be flagged
          api_key: !secret backup_api_key      # This doesn't exist - should be flagged

  # Test with templates - should not be flagged for validation
  conditional_notify:
    sequence:
      - service: notify.email
        data:
          message: "Template test"
          # Template usage - should be ignored by validation
          token: "{{ states('input_text.secret_token') }}"
