# Test script reference for goto definition
automation:
  - id: test_definition
    alias: "Test Definition"
    trigger:
      - platform: state
        entity_id: binary_sensor.motion
        to: "on"
    action:
      # Reference scripts by name to test goto definition
      - service: script.test_script_1
      - service: script.test_script_2
      - service: script.another_script
