# Test nested secrets
sensor:
  - platform: template
    sensors:
      test_sensor:
        value_template: "{{ states('sensor.temp') }}"
        friendly_name: !secret email_password
        api_key: !secret api_key

notify:
  - platform: telegram
    name: telegram
    chat_id: !secret telegram_chat_id
    api_key: !secret api_key

rest_command:
  test_command:
    url: !secret database_password
    method: POST
    headers:
      Authorization: "Bearer !secret api_key"
