# Test secrets references
homeassistant:
  name: !secret database_password
  
http:
  base_url: !secret api_key
  api_password: !secret telegram_token

# Test with different formatting
automation:
  - alias: "Test automation"
    trigger:
      platform: state
      entity_id: sensor.test
    action:
      - service: notify.test
        data:
          message: !secret email_password
          api_key: !secret api_key
