# Test invalid secret syntax
homeassistant:
  name: secret welcome         # Missing !
  base_url: !secretwelcome     # Missing space
  api_key: ! secret api_key    # Extra space
  value: "!secret welcome"     # In quotes
  comment: # !secret welcome   # In comment
