# Test file for action validation functionality
# This file demonstrates the new service/action validation feature

automation:
  - id: test_action_validation
    alias: "Test Action Validation"
    description: "Test automation to validate action detection"
    trigger:
      - platform: state
        entity_id: binary_sensor.motion
        to: "on"
    action:
      # Valid actions that should exist in most HA instances
      - service: light.turn_on
        target:
          entity_id: light.living_room
        data:
          brightness: 255
      
      # Unknown action that should be flagged
      - service: light.unknown_service_name
        target:
          entity_id: light.kitchen
      
      # Using action instead of service (also valid)
      - action: switch.turn_off
        target:
          entity_id: switch.outlet
      
      # Unknown action that should be flagged
      - action: unknown_domain.fake_service
        target:
          entity_id: light.bedroom

script:
  test_script:
    sequence:
      # Valid homeassistant action
      - service: homeassistant.turn_off
        target:
          entity_id: light.all_lights
      
      # Invalid action with wrong format (should be ignored)
      - service: not_a_valid_format
        target:
          entity_id: light.test
      
      # Template action (should be ignored)
      - service: "{{ states.sensor.dynamic_service.state }}"
        target:
          entity_id: light.dynamic
      
      # Secret action (should be ignored)  
      - service: !secret my_service
        target:
          entity_id: light.secret
          
      # Another unknown action that should be flagged
      - service: media_player.nonexistent_action
        target:
          entity_id: media_player.living_room
