name: Language Sevice

on:
  push:
    paths:
      - "src/language-service/*"
      - ".github/*"
  pull_request:
    paths:
      - "src/language-service/*"
      - ".github/*"

jobs:
  language-service:
    name: Language Service
    runs-on: ubuntu-latest

    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v6

      - name: 🏗 Set up NodeJS
        uses: actions/setup-node@v6.1.0
        with:
          node-version: "18"

      - name: 🏗 Install NodeJS packages
        working-directory: src/language-service
        run: npm install

      - name: 🚀 Run Linter
        working-directory: src/language-service
        run: npm run lint

      - name: 🚀 Build Schema
        working-directory: src/language-service
        run: npm run schema

      - name: 🚀 Run Compile
        working-directory: src/language-service
        run: npm run compile

      - name: 🏗 Create .npmrc
        if: success() && github.ref == 'refs/heads/master'
        run:
          echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" >> ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 🚀 Publish to NPM Registry
        if: success() && github.ref == 'refs/heads/master'
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish src/language-service

    # - name: NPM Publish to Registry
    #   uses: actions/npm@master
    #   if: success() && github.ref == 'refs/heads/master'
    #   env:
    #     NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    #   with:
    #     args: publish src/language-service
